### ISSUE TITLE
Command not found

### ISSUE THREAD

**Issue by nicomegadrive** [SudoMaker/midi2vgm#1]
Hi,

I followed the steps to install / compile midi2vgm on Ubuntu, when in the build folder I try to run : midi2vgm_opl3 "nameofthemidifile" in the same folder and the terminal keeps returning "command not found".

Did I do something wrong in the process ?

Thanks in advance for your help.

**Comment by ReimuNotMoe** [comment]
run `ls -ahl` to see if it's in the current directory

if so, you should add `./` before the executable name: `./midi2vgm_opl3`
